"""Recover actual cache bytes from current Drive metadata, regardless of manifest state."""

import hashlib
from io import BytesIO
import json
from pathlib import Path
from queue import SimpleQueue
from threading import Event
from unittest.mock import Mock

import pytest


def photo(file_id, name=None, data=None):
    data = file_id.encode() if data is None else data
    return {"id": file_id, "name": name or f"{file_id}.jpg",
            "md5Checksum": hashlib.md5(data).hexdigest(), "size": str(len(data))}


def album(folder_id, photos=(), name=None):
    return {"id": folder_id, "name": name or folder_id, "photos": list(photos)}


def setup_sync(app, monkeypatch, remote):
    listing = Mock(return_value=remote)
    download = Mock(side_effect=lambda file_id, destination, **kwargs: destination.write_bytes(file_id.encode()))
    monkeypatch.setattr(app.sync, "list_albums", listing)
    monkeypatch.setattr(app.sync, "download_photo", download)
    return listing, download


def cached(app):
    return {str(path.relative_to(app.cache)): path.read_bytes() for path in app.slideshow.get_cached_photos()}


def image_bytes(image_format, size, color="blue"):
    from PIL import Image

    output = BytesIO()
    with Image.new("RGB", size, color) as image:
        image.save(output, format=image_format, quality=95)
    return output.getvalue()


def test_upload_dates_order_downloads_and_survive_offline_without_redownloading(app, monkeypatch):
    from client.cache import CacheIndex
    old = {**photo("old"), "createdTime": "2024-01-01T00:00:00Z", "modifiedTime": "2026-09-13T00:00:00Z"}
    new = {**photo("new"), "createdTime": "2026-09-12T00:00:00Z"}
    middle = {**photo("middle"), "createdTime": "2025-01-01T00:00:00Z"}
    remote = [album("kids", [old, middle]), {**album("summer", [new]), "modifiedTime": "2026-09-12T00:00:00Z"}]
    listing, download = setup_sync(app, monkeypatch, remote)
    queue = SimpleQueue()
    assert app.sync.sync_photos(queue).success
    assert [call.args[0] for call in download.call_args_list] == ["new", "middle", "old"]
    assert [queue.get_nowait().stem for _ in range(3)] == ["new", "middle", "old"]
    manifest = json.loads((app.cache / app.sync.MANIFEST).read_text())
    assert manifest["photos"]["old"]["created"] == old["createdTime"]
    assert manifest["folder_metadata"]["summer"]["modified"] == remote[1]["modifiedTime"]
    old["modifiedTime"] = "2026-09-14T00:00:00Z"
    assert app.sync.sync_photos().success
    assert download.call_count == 3
    listing.side_effect = ConnectionError("Offline")
    assert not app.sync.sync_photos().success
    # A new process can still order and label photos from the saved metadata.
    index = CacheIndex(app.cache)
    assert [p.stem for p in index.photos()] == ["new", "middle", "old"]
    assert index.folder_details()["kids"].updated.date().isoformat() == "2026-09-14"


def test_sync_mirrors_albums_empty_folders_and_reuses_one_service(app, monkeypatch):
    listing, download = setup_sync(app, monkeypatch, [album("kids", [photo("one", "family.jpg")]),
        album("summer", [photo("two", "family.jpg")]), album("empty")])
    queue = SimpleQueue()
    assert app.sync.sync_photos(queue).success
    assert cached(app) == {"kids/family.jpg": b"one", "summer/family.jpg": b"two"}
    assert app.slideshow.get_cached_folders() == ["empty", "kids", "summer"]
    service = app.sync.get_drive_service.return_value
    listing.assert_called_once_with("test-folder", service=service, stop_event=None)
    assert all(call.kwargs['service'] is service for call in download.call_args_list)
    service.close.assert_called_once()
    assert queue.get_nowait() == app.cache / "kids/family.jpg"
    assert queue.get_nowait() == app.cache / "summer/family.jpg"
    assert app.sync.sync_photos(queue).success
    assert download.call_count == 2
    assert queue.empty()


def test_iphone_photo_is_converted_once_to_same_stem_jpeg_and_never_cached_as_heic(
    app, monkeypatch,
):
    from PIL import Image

    source = (Path(__file__).parent / "fixtures/wide-red.heic").read_bytes()
    remote = [album("kids", [photo("phone", "portrait.HEIC", source)])]
    listing = Mock(return_value=remote)
    download = Mock(side_effect=lambda file_id, path, **kwargs: path.write_bytes(source))
    monkeypatch.setattr(app.sync, "list_albums", listing)
    monkeypatch.setattr(app.sync, "download_photo", download)
    queue = SimpleQueue()

    assert app.sync.sync_photos(queue).success
    destination = app.cache / "kids/portrait.jpg"
    assert queue.get_nowait() == destination
    assert destination.exists()
    assert not list(app.cache.rglob("*.heic")) and not list(app.cache.rglob("*.HEIC"))
    with Image.open(destination) as converted:
        assert converted.format == "JPEG"
        assert converted.size == (160, 40)
        assert converted.quantization[0][:8] == [8, 6, 5, 8, 12, 20, 26, 31]  # quality 75

    # The generated bytes have their own integrity hash, so an unchanged
    # source is not downloaded or converted again.
    assert app.sync.sync_photos(queue).success
    assert download.call_count == 1
    assert queue.empty()

    # A Drive rename reuses the verified JPEG derivative without decoding the
    # HEIC again, while exposing only the new same-stem name to playback.
    remote[0]["photos"][0]["name"] = "renamed.heic"
    assert app.sync.sync_photos(queue).success
    assert download.call_count == 1
    assert queue.get_nowait() == app.cache / "kids/renamed.jpg"
    assert not destination.exists()


def test_large_jpeg_is_bounded_to_1600x900_and_reused(app, monkeypatch):
    from PIL import Image

    source = image_bytes("JPEG", (2400, 1350))
    remote = [album("kids", [photo("large", "large.jpg", source)])]
    download = Mock(side_effect=lambda file_id, path, **kwargs: path.write_bytes(source))
    monkeypatch.setattr(app.sync, "list_albums", Mock(return_value=remote))
    monkeypatch.setattr(app.sync, "download_photo", download)

    assert app.sync.sync_photos().success
    destination = app.cache / "kids/large.jpg"
    with Image.open(destination) as normalized:
        assert normalized.format == "JPEG"
        assert normalized.size == (1600, 900)
        assert normalized.quantization[0][:8] == [5, 3, 3, 5, 7, 12, 15, 18]  # quality 85
    manifest = json.loads((app.cache / app.sync.MANIFEST).read_text())
    entry = manifest["photos"]["large"]
    assert entry["processing"] == "fit-1600x900-other85-iphone75-v3"
    assert len(entry["cache_sha256"]) == 64

    assert app.sync.sync_photos().success
    assert download.call_count == 1


def test_portrait_and_non_jpeg_photos_use_same_aspect_ratio_cap(app, tmp_path):
    from PIL import Image

    for suffix, image_format in (("jpg", "JPEG"), ("png", "PNG"), ("webp", "WEBP")):
        source = tmp_path / f"source.{suffix}"
        destination = tmp_path / f"cached-{suffix}.part"
        source.write_bytes(image_bytes(image_format, (1000, 2000)))
        entry = {"converted": False, "path": f"kids/photo.{suffix}"}

        assert app.sync._prepare_cached_photo(source, destination, entry)
        with Image.open(destination) as normalized:
            assert normalized.size == (450, 900)


def test_iphone_conversion_uses_same_cap_and_small_jpeg_stays_byte_identical(app, tmp_path):
    from PIL import Image

    large = tmp_path / "phone-source.jpg"
    converted = tmp_path / "phone-publication.part"
    large.write_bytes(image_bytes("JPEG", (2400, 1350)))
    assert app.sync._prepare_cached_photo(
        large, converted, {"converted": True, "path": "kids/phone.jpg"})
    with Image.open(converted) as image:
        assert image.size == (1600, 900)

    small = tmp_path / "small.jpg"
    unused = tmp_path / "unused.part"
    payload = image_bytes("JPEG", (1366, 768))
    small.write_bytes(payload)
    assert not app.sync._prepare_cached_photo(
        small, unused, {"converted": False, "path": "kids/small.jpg"})
    assert small.read_bytes() == payload
    assert not unused.exists()


def test_iphone_jpeg_name_collision_is_disambiguated(app, monkeypatch):
    heic = (Path(__file__).parent / "fixtures/wide-red.heic").read_bytes()
    from PIL import Image
    jpeg_file = BytesIO()
    with Image.new("RGB", (2, 2), "blue") as image:
        image.save(jpeg_file, format="JPEG")
    payloads = {"heic": heic, "jpeg": jpeg_file.getvalue()}
    remote = [album("kids", [
        photo("heic", "portrait.heic", payloads["heic"]),
        photo("jpeg", "portrait.jpg", payloads["jpeg"]),
    ])]
    monkeypatch.setattr(app.sync, "list_albums", Mock(return_value=remote))
    monkeypatch.setattr(app.sync, "download_photo",
                        lambda file_id, path, **kwargs: path.write_bytes(payloads[file_id]))
    assert app.sync.sync_photos().success
    names = [path.name for path in app.slideshow.get_cached_photos()]
    assert len(names) == 2
    assert all(Path(name).suffix.lower() == ".jpg" for name in names)
    assert len({name.casefold() for name in names}) == 2


@pytest.mark.parametrize('damage', ['missing', 'empty', 'wrong_same_size'])
def test_changed_cache_bytes_are_repaired_even_with_unchanged_manifest(app, monkeypatch, damage):
    _, download = setup_sync(app, monkeypatch, [album('kids', [photo('one')])])
    app.sync.sync_photos()
    path = app.cache / 'kids/one.jpg'
    if damage == 'missing':
        path.unlink()
    else:
        path.write_bytes(b'' if damage == 'empty' else b'BAD')
    assert app.sync.sync_photos().success
    assert path.read_bytes() == b'one'
    assert download.call_count == 2


@pytest.mark.parametrize('manifest_state', ['missing', 'corrupt'])
def test_manifest_rebuild_uses_drive_and_removes_stale_album_photos(app, monkeypatch, manifest_state):
    listing, _ = setup_sync(app, monkeypatch, [album('kids', [photo('one'), photo('deleted')])])
    app.sync.sync_photos()
    manifest = app.cache / app.sync.MANIFEST
    if manifest_state == 'missing':
        manifest.unlink()
    else:
        manifest.write_text('{bad json')
    listing.return_value = [album('kids', [photo('one')])]
    assert app.sync.sync_photos().success
    assert cached(app) == {'kids/one.jpg': b'one'}


def test_interrupted_filename_swap_recovers_from_drive_checksums(app, monkeypatch):
    listing, download = setup_sync(app, monkeypatch, [album('kids', [photo('a'), photo('b')])])
    app.sync.sync_photos()
    listing.return_value = [album('kids', [photo('a', 'b.jpg'), photo('b', 'a.jpg')])]
    replace = Path.replace
    with monkeypatch.context() as interrupted:
        def fail_manifest(path, target):
            if Path(target).name == app.sync.MANIFEST:
                raise OSError('Interrupted manifest write')
            return replace(path, target)
        interrupted.setattr(Path, 'replace', fail_manifest)
        assert not app.sync.sync_photos().success
    assert app.sync.sync_photos().success
    assert cached(app) == {'kids/a.jpg': b'b', 'kids/b.jpg': b'a'}
    assert download.call_count == 2


def test_rename_move_edit_and_deletion(app, monkeypatch):
    listing, download = setup_sync(app, monkeypatch, [album('kids', [photo('one'), photo('deleted')]), album('empty')])
    app.sync.sync_photos()
    listing.return_value = [album('renamed', [photo('one', 'moved.jpg')])]
    assert app.sync.sync_photos().success
    assert cached(app) == {'renamed/moved.jpg': b'one'}
    assert download.call_count == 2
    listing.return_value = [album('renamed', [photo('one', 'moved.jpg', b'edited')])]
    download.side_effect = lambda file_id, path, **kwargs: path.write_bytes(b'edited')
    assert app.sync.sync_photos().success
    assert cached(app) == {'renamed/moved.jpg': b'edited'}
    listing.return_value = []
    assert app.sync.sync_photos().success
    assert app.slideshow.get_cached_folders() == []


def test_duplicate_unsafe_and_long_names_preserve_supported_extensions(app, monkeypatch):
    _, download = setup_sync(app, monkeypatch, [album('a', [photo('one', '../photo.jpg'), photo('two', '../photo.jpg'),
        photo('long', 'x' * 240 + '.jpg')], '../kids'), album('b', [photo('three')], '../kids')])
    assert app.sync.sync_photos().success
    assert len(cached(app)) == 4
    assert {p.read_bytes() for p in app.slideshow.get_cached_photos()} == {b'one', b'two', b'three', b'long'}
    assert app.sync.sync_photos().success
    assert download.call_count == 4


def test_ssl_listing_failure_preserves_cache_and_is_visible_until_recovery(app, monkeypatch):
    import ssl
    from client.status import RuntimeStatus
    status = RuntimeStatus()
    listing, download = setup_sync(app, monkeypatch, [album('kids', [photo('one')])])
    app.sync.sync_photos()
    manifest = (app.cache / app.sync.MANIFEST).read_bytes()
    listing.side_effect = ssl.SSLError('Wi-Fi disconnected')
    assert not app.sync.sync_photos(status=status).success
    assert cached(app) == {'kids/one.jpg': b'one'}
    assert (app.cache / app.sync.MANIFEST).read_bytes() == manifest
    assert status.snapshot()[0]['active']
    assert 'SSLError' in status.snapshot()[0]['message']
    assert status.network_problem()
    assert not status.panel_snapshot()
    listing.side_effect = None
    assert app.sync.sync_photos(status=status).success
    assert not status.snapshot()[0]['active']
    assert not status.network_problem()
    assert not status.panel_snapshot()
    assert download.call_count == 1


def test_failed_update_keeps_old_bytes_and_never_publishes_bad_download(app, monkeypatch):
    listing, download = setup_sync(app, monkeypatch, [album('kids', [photo('one')])])
    app.sync.sync_photos()
    listing.return_value = [album('kids', [photo('one', data=b'edited')])]
    queue = SimpleQueue()
    download.side_effect = lambda file_id, path, **kwargs: path.write_bytes(b'wrong!')
    assert not app.sync.sync_photos(queue).success
    assert cached(app) == {'kids/one.jpg': b'one'}
    assert queue.empty()
    download.side_effect = lambda file_id, path, **kwargs: path.write_bytes(b'edited')
    assert app.sync.sync_photos(queue).success
    assert queue.get_nowait() == app.cache / 'kids/one.jpg'
    assert cached(app) == {'kids/one.jpg': b'edited'}


def test_partial_failure_retries_and_each_photo_is_queued_immediately(app, monkeypatch):
    _, download = setup_sync(app, monkeypatch, [album('kids', [photo('one'), photo('two')])])
    queue = SimpleQueue()
    attempts = []
    def transfer(file_id, path, **kwargs):
        attempts.append(file_id)
        assert queue.empty()
        path.write_bytes(b'partial')
        if attempts == ['one']:
            raise ConnectionError('Interrupted')
        path.write_bytes(file_id.encode())
    download.side_effect = transfer
    assert not app.sync.sync_photos(queue).success
    assert queue.get_nowait() == app.cache / 'kids/two.jpg'
    assert app.sync.sync_photos(queue).success
    assert queue.get_nowait() == app.cache / 'kids/one.jpg'
    assert attempts == ['one', 'two', 'one']
    assert not list(app.cache.glob('.sync-*'))


def test_second_process_lock_and_cooperative_cancellation(app, monkeypatch):
    _, download = setup_sync(app, monkeypatch, [album('kids', [photo('one')])])
    with app.sync.cache_lock():
        result = app.sync.sync_photos()
        assert not result.success
        assert 'Another sync' in result.error
    stop = Event()
    stop.set()
    assert app.sync.sync_photos(stop_event=stop).cancelled
    download.assert_not_called()
    assert app.sync.sync_photos().success


def test_missing_remote_checksum_forces_download_instead_of_trusting_manifest(app, monkeypatch):
    remote = photo('one')
    remote.pop('md5Checksum')
    _, download = setup_sync(app, monkeypatch, [album('kids', [remote])])
    assert app.sync.sync_photos().success
    assert app.sync.sync_photos().success
    assert download.call_count == 2


def test_partly_applied_swap_recovers_missing_bytes_from_drive(app, monkeypatch):
    listing, download = setup_sync(app, monkeypatch, [album('kids', [photo('a'), photo('b')])])
    app.sync.sync_photos()
    listing.return_value = [album('kids', [photo('a', 'b.jpg'), photo('b', 'a.jpg')])]
    replace = Path.replace
    with monkeypatch.context() as interrupted:
        def fail_second_photo(path, target):
            if Path(target).name == 'a.jpg':
                raise OSError('Interrupted second publication')
            return replace(path, target)
        interrupted.setattr(Path, 'replace', fail_second_photo)
        assert not app.sync.sync_photos().success
    assert app.sync.sync_photos().success
    assert cached(app) == {'kids/a.jpg': b'b', 'kids/b.jpg': b'a'}
    assert download.call_count == 3  # Lost b bytes were fetched from Drive, not a backup.


def test_lock_is_enforced_across_processes(app):
    import subprocess
    import sys
    with app.sync.cache_lock():
        process = subprocess.run([sys.executable, '-c',
            'from client.sync import sync_photos; result = sync_photos(); '
            'assert not result.success and "Another sync" in result.error'],
            capture_output=True, text=True, timeout=10)
    assert process.returncode == 0, process.stderr
